### ISSUE TITLE
guidelines: exit code greater than 0

### ISSUE THREAD

**Issue by RavuAlHemio** [osue-tuwien/exercises#17]
The guidelines currently state:

> 3\. Im fehlerfreien Fall muß das Programm mit dem Exit-Code 0 terminieren, im Fehlerfall mit einem Exit-Code größer als 0.

However, it appears [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdlib.h.html) defines `EXIT_FAILURE` only as *non-zero*, not necessarily as *greater than zero*. This has almost caused one student to replace all occurrences of `return EXIT_FAILURE` with `return 1`.

It might be a good idea to add to the guidelines that exiting with `EXIT_FAILURE` in case of an error is always okay [i.e. even if the platform happens to define `EXIT_FAILURE` to a negative value].

**Comment by dratasich** [comment]
Thanks a lot.
The [glibc](https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html) defines an exit status from 0 to 255. I guess this is where the guideline resulted from.
We will add the suggestion to use EXIT_SUCCESS/EXIT_FAILURE.
