### ISSUE TITLE
genpdfs.sh script doesn't work

### ISSUE THREAD

**Issue by Nicram01** [osue-tuwien/exercises#21]
The script genpdfs.sh iterates through all the files and generates a pdf document with pdflatex when the file ends with ".tex". The issue is that there is one file named BonusExercise.tex from which a pdf document can not be created, because it doesn't have the necessary wrapping for a latex document and is used as a section in other documents. That is why the script crashes when it is run. I fixed the issue by skipping the iteration when the file is found. The code that I implemented at the start of the iteration is posted below.

```
if [ $file ==  "./regular/2/BonusExercise.tex" ]; 
then
 continue
fi
```

**Comment by oddest-prime** [comment]
Thanks for reporting.
Fixed in ae51ca75f163c73222c447cc18b6af4e7b3a2c1b
